# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "uiiafux-dd04772"
user = "qsong"
password = "WWfreemind1"
role = "ACCOUNTADMIN"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"

